README.md, wdl-ci.config.json, workflows/cohort_analysis/cohort_analysis.wdl, workflows/cohort_analysis/inputs.json, workflows/main.wdl, workflows/sample_analysis/sample_analysis.wdl
- Depends on https://github.com/PacificBiosciences/wdl-common/pull/19
- HiPhase set to phase both DeepVariant and PBSV output, using aligned HiFi BAMs.
- For sample_analysis, generates haplotagged BAMs as well.
- For cohort_analysis, simultaneously phases all samples in cohort, but does not haplotag BAMs.
- Documentation updated.
=> Replace WhatsHap with HiPhase

wdl-ci.config.json, workflows/cohort_analysis/cohort_analysis.wdl, workflows/humanwgs_structs.wdl, workflows/sample_analysis/sample_analysis.wdl
Split `pbsv call` task into 14 sets of ~150-300Mbp, never splitting chromosomes.
- depends on changes to pbsv_call and the addition of concat_vcf in https://github.com/PacificBiosciences/wdl-common/pull/29
- depends on a new input, `"pbsv_splits": "dataset/GRCh38/human_GRCh38_no_alt_analysis_set.pbsv_splits.json"`, which is a json file with an `Array[Array[String]]`.  Each `Array[String]` is a set of chromosomes to be processed by the same task.
=> Parallelize pbsv call

wdl-ci.config.json, workflows/cohort_analysis/cohort_analysis.wdl, workflows/sample_analysis/sample_analysis.wdl
concat_vcf receives an array of vcf.gz and an array of vcf.gz.tbi. Cromwell groups each pair together in a separate inputs folder (because they were generated by the same upstream task), but miniwdl provides each input independently in its own directory, so the index isn't grouped with the VCF.  This PR links all inputs together into a single directory so bcftools can find the indices.
=> Fix for concat_vcf for miniwdl.  Link all inputs into a single directory so that vcfs and indices are together.

wdl-ci.config.json, workflows/main.wdl, workflows/sample_analysis/sample_analysis.wdl
If the input BAM doesn't cover any of the paraphase regions, there are no VCFs to tar.
```bash
tar: HG006_vcfs/*.vcf: Cannot stat: No such file or directory
```
This change makes the VCF tarball an optional output, and only creates it if VCFs have been created.
=> fix: Handle missing output for paraphase.

LICENSE, README.md
- Sample and cohort IDs should be limited to alphanumeric characters, dashes (`-`), and underscores (`_`).  These are not enforced hard restrictions, but there may be unexpected behavior.  (Related to #113.)
- `deepvariant_version` is available to support development work, but because of frequent API changes to DeepVariant, only 1.6 is supported in this branch.  Only DeepVariant v1.5 is supported in the v1 branch of this workflow.
=> Clarifications in documentation.

workflows/family.wdl, workflows/singleton.wdl
This pull request includes changes to fix typo in the `humanwgs_family` and `humanwgs_singleton` workflows.
Changes:
* [`workflows/family.wdl`](diffhunk://#diff-100e9434aeb81d7cba288a9151d468da2d50438dcf92924b12ba4b5f3bbf05bbL175-R175): Corrected the statistical key from `read_length_min` to `read_length_mean` in the `stats` map.
* [`workflows/singleton.wdl`](diffhunk://#diff-d66f13d2d26c668befcdb8ee11babff11b27e1f29bbffda10c4b92258586a5a6L149-R149): Corrected the statistical key from `read_length_min` to `read_length_mean` in the `stats` map.
=> fix stats file typo

.github/workflows/lint-test-workflows.yml, README.md, wdl-ci.config.json
- In v2.0.5, backslashes in `\t`, `\n`, and other special characters were escaped to address [SC1117](https://www.shellcheck.net/wiki/SC1117).  This introduced bugs that appeared at various parts of the analysis workflow depending on the backend.  Reverting all of these changes until we have a better way of dealing with this.
=> Revert SC1117 fixes that caused issues with miniwdl.

wdl-ci.config.json
- updated trgt version
- changed trgt `samtools sort` to use 8 threads to address OOM
- changed coverage_dropouts to use pb_wdl_base
- created new dockerfile: https://github.com/PacificBiosciences/wdl-dockerfiles/pull/71
- updated wdl-common: https://github.com/PacificBiosciences/wdl-common/pull/43
- pushed wiki branch feature/trgt-v1.4.1
=> Updated to TRGT v1.4.1.

wdl-ci.config.json
Release fixes behavior where `SA` tags were not stripped from aligned input.
=> Update to pbmm2 v1.16.99 prerelease.

wdl-ci.config.json, workflows/downstream/downstream.wdl, workflows/family.wdl, workflows/singleton.wdl
- Remove StarPhase outputs that are not allowed as PharmCAT input (PharmGKB/PharmCAT/issues/204)
- `NO_READS` is used in StarPhase output to indicate no-calls.
- `NO_MATCH` is used when StarPhase can't match the variants to a known allele.
- This workaround removes `NO_READS`/`NO_MATCH` outputs.
- Only attempt to run PharmCAT if at least one PharmCAT region has `depth > pharmcat_min_coverage`
=> Gracefully handle low depth samples with StarPhase/PharmCAT

wdl-ci.config.json, workflows/downstream/downstream.wdl, workflows/family.inputs.json, workflows/family.wdl, workflows/joint/inputs.json, workflows/joint/joint.wdl, workflows/singleton.wdl, workflows/upstream/upstream.wdl
Added sawfish v0.12.7.
- Added `sawfish_discover` and `sawfish_call` tasks.
- `sawfish_call` optionally outputs supporting reads json (default `true`) for SVTopo
- Removed pbsv task calls from workflow and replaced with sawfish task calls.
- Added tests for sawfish tasks and removed tests for pbsv tasks.
To do:
=> Added sawfish.

workflows/downstream/downstream.wdl, workflows/family.wdl, workflows/singleton.wdl, workflows/upstream/upstream.wdl
Moved the coverage_dropouts task from upstream.wdl to downstream.wdl, where it can take advantage of the phased reads to report haplotype dropouts.
=> Move coverage_dropouts to downstream.

workflows/family.wdl, workflows/singleton.wdl, workflows/upstream/upstream.wdl
Inferred sex is compared to the reported sex, and if there is a disagreement, a new `String qc_sex` message is emitted by upstream.  These messages are gathered at top level `Array[String?] qc_messages` and emitted as output.
=> Compare inferred to reported sex for QC

wdl-ci.config.json, workflows/downstream/downstream.wdl, workflows/family.wdl, workflows/singleton.wdl, workflows/upstream/upstream.wdl
- remove components from pbmm2_align task that gather stats about read length and quality
- remove task to merge per-bam stats and plot read length and quality
- remove components from hiphasse task that gather stats about mapping and alignment
- add a new bam_stats task that extracts all tasks in a single pass through the BAM and replaces the outputs from the removed components
=> Refactor tasks that extract stats from BAM files so that we only iterate through the BAM once.

workflows/downstream/downstream.wdl, workflows/family.wdl, workflows/singleton.wdl, workflows/upstream/upstream.wdl
Moved the coverage_dropouts task from upstream.wdl to downstream.wdl, where it can take advantage of the phased reads to report haplotype dropouts.
v2 backport of #200
(cherry picked from commit 0542f795ebebc21f2115480f00ffeadf2b453138)
=> Move coverage dropouts (v2)

docs/backend-gcp.md, docs/family.md, docs/singleton.md, wdl-ci.config.json, workflows/downstream/inputs.json, workflows/family.inputs.json, workflows/family.wdl, workflows/joint/inputs.json, workflows/singleton.inputs.json, workflows/singleton.wdl, workflows/tertiary/inputs.json, workflows/tertiary/tertiary.wdl, workflows/upstream/inputs.json
- add cpuPlatform to every task
- add cpuPlatform to backend_configuration
- add cpuPlatform input to family and singleton entrypoints
- document input in singleton and family docs
- document input in backend-gcp doc
- update wdl-ci tests
=> Add the `cpuPlatform` runtime attribute to support the workflow in GCP zones that lack n1 nodes.

docs/family.md, docs/singleton.md, wdl-ci.config.json, workflows/downstream/downstream.wdl, workflows/family.wdl, workflows/joint/joint.wdl, workflows/singleton.wdl, workflows/upstream/upstream.wdl
sawfish:
- Remove `sex` and related files from inputs.
- Add `--verbose` to all filesystem command calls.
- Switch to long form arguments for all command calls, when available.
- Clean up compressed/decompressed files at the end of each task.
- Pass `supporting_reads_json` up to main workflow outputs.
sv_stats:
- Remove `InvBreakpoint` filtered event counts from output.
- Require that all counted events are `FILTER="PASS"` and `ALT` genotypes.
- Filter "sequence swap" complex variants from the INS and DEL counts, and put them in a separate `SWAP` category.  These are variants where both the `REF` and `ALT` are longer than 1bp.
=> Updates to sawfish and sv_stats.

wdl-ci.config.json
In DeepVariant >1.8, `example_tfrecord_tars` are needed by postprocess_variants.  They were added to the task, but disk_size was not increased.  We missed it in testing because it's not used by HPC or HealthOmics.
fixes #234
=> fix: Add example_tfrecord_tars to disk_size for deepvariant_postprocess_variants.

backends/aws-healthomics/aws_ecr_push_tag_images.sh
Previously, if the user runs this script from an arm64 system, they would pull/push the arm64 image for PharmCat and get the following error for PharmCat tasks at runtime: `exec /bin/bash: exec format error`.
=> fix: Force linux/amd64 platform in aws ecr push script.

docs/family.md, docs/ref_map.md, docs/singleton.md, docs/trgt.md, wdl-ci.config.json, workflows/downstream/downstream.wdl, workflows/downstream/inputs.json, workflows/family.inputs.json, workflows/family.wdl, workflows/humanwgs_structs.wdl, workflows/process_trgt_catalog/inputs.json, workflows/process_trgt_catalog/process_trgt_catalog.wdl, workflows/singleton.inputs.json, workflows/singleton.wdl, workflows/upstream/inputs.json, workflows/upstream/upstream.wdl
- created a `trgt_tandem_repeat_bed` where we've flagged CANVAS_RFC1, FRDA_FXN, SCA27B_FGF14 with `;INCLUDE_FAIL_READS` in column 4
- new subworkflow `process_trgt_catalog.wdl` that
- removes the `;INCLUDE_FAIL_READS` flag to produce a clean trgt catalog (in case this would interfere with trgt functions)
- extracts records flagged with `;INCLUDE_FAIL_READS` into a `include_fail_reads_bed` file
- uses this `include_fail_reads_bed` to create a "bait" fasta with these loci +/- 10kb
- adds a new optional `fail_reads` input for each sample
- if 1) `fail_reads` have been provided and 2) there were records flagged with `;INCLUDE_FAIL_READS`
- align `fail_reads` to the bait fasta
- realign baited reads to the GRCh38 reference
- filter the GRCh38 aligned fail_reads to only include reads mapped to …
=> feat: Use fail_reads for TRGT
